### ISSUE TITLE
Incompatibility with Mendix 9.1

### ISSUE THREAD

**Issue by lordlothar99** [mendix/EmailModuleWithTemplates#40]
56 errors found when project is migrated to Mendix 9.1.

**Comment by jurretanjamx** [comment]
The 56 errors are dependencies on other modules that are available in the Marketplace (MxModel reflection and Encryption). 
The documentation both in the module and the Marketplace refer to this. 
These modules are not included on purpose since this will create too many update dependencies for us to maintain. 
See [here](https://docs.mendix.com/appstore/modules/email-with-templates) for more information.
